data:

  path:
    starter_materials: "/home/nawaf/workflows/superionic_ai/src/data/start_mat.yaml"
    processed_save_path: "/home/nawaf/workflows/superionic_ai/src/data/processed_cifs"
    relaxed_save_path: "/home/nawaf/workflows/superionic_ai/src/data/relaxed_cifs"
    raw_save_path: "/home/nawaf/workflows/superionic_ai/src/data/raw_cifs"

  substitution:
    atom_to_replace: "Li"
    replacement_atom: "Na"


model:

  m3gnet:
    checkpoints: 
      formation_energy_checkpoint: "/home/nawaf/workflows/superionic_ai/models/m3gnet_models/matbench_mp_e_form/0/m3gnet"
      bandgap_checkpoint: "/home/nawaf/workflows/superionic_ai/models/m3gnet_models/matbench_mp_gap/0/m3gnet"
    
    relaxer:
      fmax: 0.1
      steps: 500
      traj_file: None
      interval: 1
      verbose: True

workflow:

  screen_cutoffs:
    formation_energy: 0.0
    bandgap: 1.0






    
  
  